"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createProjectMetadata = exports.RECENT_PROJECTS_KEY = exports.PROJECT_VERSION = exports.PROJECT_FORMAT = exports.PROJECT_FILE_EXTENSION = exports.AUTOSAVE_KEY = exports.AUTOSAVE_INTERVAL_MS = exports.RecentProjects = exports.recentProjects = exports.serializeProjectDocument = exports.createProjectDocument = exports.loadProjectDocument = exports.ProjectManager = exports.projectManager = exports.AutosaveManager = exports.autosaveManager = void 0;
var AutosaveManager_1 = require("./AutosaveManager");
Object.defineProperty(exports, "autosaveManager", { enumerable: true, get: function () { return AutosaveManager_1.autosaveManager; } });
Object.defineProperty(exports, "AutosaveManager", { enumerable: true, get: function () { return AutosaveManager_1.AutosaveManager; } });
var ProjectManager_1 = require("./ProjectManager");
Object.defineProperty(exports, "projectManager", { enumerable: true, get: function () { return ProjectManager_1.projectManager; } });
Object.defineProperty(exports, "ProjectManager", { enumerable: true, get: function () { return ProjectManager_1.ProjectManager; } });
var ProjectLoader_1 = require("./ProjectLoader");
Object.defineProperty(exports, "loadProjectDocument", { enumerable: true, get: function () { return ProjectLoader_1.loadProjectDocument; } });
var ProjectSerializer_1 = require("./ProjectSerializer");
Object.defineProperty(exports, "createProjectDocument", { enumerable: true, get: function () { return ProjectSerializer_1.createProjectDocument; } });
Object.defineProperty(exports, "serializeProjectDocument", { enumerable: true, get: function () { return ProjectSerializer_1.serializeProjectDocument; } });
var RecentProjects_1 = require("./RecentProjects");
Object.defineProperty(exports, "recentProjects", { enumerable: true, get: function () { return RecentProjects_1.recentProjects; } });
Object.defineProperty(exports, "RecentProjects", { enumerable: true, get: function () { return RecentProjects_1.RecentProjects; } });
var ProjectVersion_1 = require("./ProjectVersion");
Object.defineProperty(exports, "AUTOSAVE_INTERVAL_MS", { enumerable: true, get: function () { return ProjectVersion_1.AUTOSAVE_INTERVAL_MS; } });
Object.defineProperty(exports, "AUTOSAVE_KEY", { enumerable: true, get: function () { return ProjectVersion_1.AUTOSAVE_KEY; } });
Object.defineProperty(exports, "PROJECT_FILE_EXTENSION", { enumerable: true, get: function () { return ProjectVersion_1.PROJECT_FILE_EXTENSION; } });
Object.defineProperty(exports, "PROJECT_FORMAT", { enumerable: true, get: function () { return ProjectVersion_1.PROJECT_FORMAT; } });
Object.defineProperty(exports, "PROJECT_VERSION", { enumerable: true, get: function () { return ProjectVersion_1.PROJECT_VERSION; } });
Object.defineProperty(exports, "RECENT_PROJECTS_KEY", { enumerable: true, get: function () { return ProjectVersion_1.RECENT_PROJECTS_KEY; } });
var ProjectMetadata_1 = require("./ProjectMetadata");
Object.defineProperty(exports, "createProjectMetadata", { enumerable: true, get: function () { return ProjectMetadata_1.createProjectMetadata; } });
